name: c-tests
on: [push, pull_request]

jobs:
  test-project:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test project with googletest.
      uses: arvsrao/googletest-action@master

# I need to compile the files
# then run the tests
